### ISSUE TITLE
Join field example with DBMS?

### ISSUE THREAD

**Issue by flashvnn** [totaljs/dbms#2]
about DBMS, can you give me full working example of join, i use code bellow but it doesn't show joined field for city, i use DBMS with Totaljs embedded db 
var builder = DBMS().find('real_estate');
var district = builder.join('city', 'city').on('district', 'id').first();
builder.callback(function(err, response) {
  console.log(response);
});

**Comment by petersirka** [comment]
Hi @flashvnn, I'll must add joins for NoSQL embedded database because I have optimized the module for PostgreSQL (primary) and MongoDB. I assumed that I'll be able to replace DB easily but there is not way because each app uses something special from DB for e.g. MongoDB aggregation or in most cases I need to use raw queries in PostgreSQL. So JOINS were added firstly for PG and then for MongoDB but this joins are a bit specificed because they are `merged` in Node.js, not in DB. But DBMS is able to join data from multiple DBs.

**Comment by aalfiann** [comment]
Sory, I've edited my comment and create new issue because this topic is not relevance with my issue.

**Comment by petersirka** [comment]
I'll solve it this week (I hope). Sorry for delay, but a lot of work.

**Comment by petersirka** [comment]
I made a mistake.... This will be solved #3 this week.
